# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(default='title', max_length=32, primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('release_time', models.DateTimeField(verbose_name='release time')),
            ],
        ),
    ]
