# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
